services:
  web:
    image: ruby:3.3.0-slim
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=development
    stdin_open: true
    tty: true
    command: bash -c "apt-get update -qq && apt-get install -y build-essential libsqlite3-dev && gem install bundler && bundle install && tail -f /dev/null"